language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "follow-your-politician-test";' -U postgres
before_deploy:
  - npm run build-client
  - rm - rf node_modules
depoy:
  skip_cleanup: true
  provider: heroku
  app: follow-your-politician
  api_key:
    secure: "rPRaq0x3ZM3C4qZ1OSqKaw5/8prjXocrh1D7yOTv8OgR/vQHpTzWOUBxLBwk3nhOOAeGJMPmjLfXoGqlmoOGzmSTg/jKa/SB27ftGbz3NZQ37IvqwnRLWt+1iw9ytffPxRrLU58MotQdoU3gmHSLdusz6jug9T4LH7TPd2N796rSUymXGTq/2aVs7neCRUAcILZ0cS2aCXhbL5uYpqU5DngzLoG5JJd4vHDpDtAzllm8He1UYWTwjcf/wtUiI5DAk2kvI7fvEHhJeI0xLCzn1sHQRjcHXHoBI/Xrv1eMQMn4QkKp3A5njl6U3u6RUD4u4DsmJPnSBEGqDGSWxcuM4+juWW14RxPSxPNL29gtnujLHettrTvELFuhnVJYIPIfg3rnAO2ttETPKyz0AJN3vwTQo57eKytn8Z60rwXaFQKAABl8e1u+87qAfWWed1LSN1KegysZKH1nKtmWZDmVidRzaNb88aQFty6JD1cemXXa/i9Ds33oD4g2K9BMztIPGkjhbs0HCBp0+Apf5WU7xvycmPUKPswAdKm2yLh1grJedKscs6PSm9LMczC7FozCnrSHJRfseFdoxbMZBgibvtrNLZnLSPy1s2DmPECdvOhqsS5ihW8vKNZpav0tCy9v3QeifD0HplcuCOlA20oIPZQ9HPPgagnXfJft2JUcjJQ="
